### PR TITLE
 create pre-training data for languages with non-Latin alphabets

### PR DESCRIPTION
**Pull request by ngoanpv**

### CODE REVIEW

**Comment by albert-copybara** [comment]
@googlebot rescan

**Comment by 0x0539** [comment]
Thanks for the changes! Would you mind updating classifier_utils.py and squad_utils.py with the new flag?

**Comment by ngoanpv** [comment]
@0x0539 Not at all, I updated the flag for  classifier_utils and squad_utils.

**Comment by 0x0539** [comment]
Thanks a lot! It looks like googlebot removed the CLA tag because one of the commits has an e-mail who hasn't signed the CLA. Can you sign the CLA with the other e-mail? I should be able to merge this pull request after that's done.

**Comment by ngoanpv** [comment]
@googlebot I fixed it.

**Comment by ngoanpv** [comment]
@0x0539 I signed the CLA.

**Comment by 0x0539** [comment]
Can you also update run_race.py?

**Comment by ngoanpv** [comment]
@0x0539  run_race.py has updated.

**Pull request closed without merging**
